---
language: node_js

cache:
  bundler: true
  apt: true
  directories:
    - node_modules

node_js:
  - "0.10"

git:
  depth: 1

install: true
#  - npm install --production --loglevel warn

notifications:
  hipchat: 3339f2786b483d04c81375df9d5193@cdnjs
  email:
    on_success: never
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f5350a3bccfdf3d07867
